version: '3'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    networks:
      - nodenet
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=peopledb  
    volumes:
      - "./mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./mysql/db:/var/lib/mysql"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: sonnesen/nginx
    container_name: nginx
    networks:
      - nodenet
    ports:
      - "8080:80"
    depends_on:
       - node
  
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: sonnesen/node
    container_name: node
    command: dockerize -wait tcp://mysql:3306 -timeout 10s npm start
    volumes:
      - ./node/app:/app
    networks:
      - nodenet
    depends_on:
      - mysql

networks:
  nodenet:
    driver: bridge