version: '3'

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=peopledb  
    volumes:
      - "./mysql/scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql/scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"
      - "./mysql/db:/var/lib/mysql"

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
       - node
  
  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    command: dockerize -wait tcp://mysql:3306 -timeout 20s npm start
    volumes:
      - ./node/app:/app
    depends_on:
      - mysql
