FROM node:18.16.1

WORKDIR /app

ENV DOCKERIZE_VERSION v0.7.0

RUN apt-get update \
    && apt-get install -y wget \
    && wget -O - https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz | tar xzf - -C /usr/local/bin \
    && apt-get autoremove -yqq --purge wget && rm -rf /var/lib/apt/lists/*

COPY ./app/package*.json .

RUN npm install

WORKDIR /app

COPY ./app/index.js .

EXPOSE 3000

CMD [ "node", "index.js" ]